### ISSUE TITLE
Add trademarks for Wireguard

### ISSUE THREAD

**Issue by donce** [mysteriumnetwork/mysterium-vpn-mobile#157]

**Comment by donce** [comment]
Acceptance criteria:
- Wireguard logo changed to "WG"
- "Wireguard" text changed to "Wireguard®"

Screens have an error - instead of TM, it should be R symbol (®)

![Screenshot 2019-03-08 at 12.25.26.png](https://images.zenhubusercontent.com/5ba247ee8c7b5425fc895855/1d3c6c93-96b2-4ee4-9d55-25bd9088330e)
![Screenshot 2019-03-08 at 12.25.21.png](https://images.zenhubusercontent.com/5ba247ee8c7b5425fc895855/8d9c9ff3-7ef9-480d-9769-5507c34225dc)

**Comment by mjankauskas** [comment]
done?

**Comment by donce** [comment]
@ignasbernotas ?

**Comment by ignasbernotas** [comment]
done
