### ISSUE TITLE
Screen transitions don't match

### ISSUE THREAD

**Issue by tadaskay** [mysteriumnetwork/mysterium-vpn-mobile#400]
1. Go to main screen (filter presets and countries are visible)
2. Click on menu (hamburger) icon
3. Menu pops up
4. Click back
5. Screen slides to the left and the main screen is shown

Expected: Menu screen should pop out in the opposite manner that it appeared and not slide to the side (feels unnatural). Similar behaviour observed in the other screens. You can check e.g. Chrome app on android (Settings screen) regarding transitions.

**Comment by Daria-Donchenko** [comment]
@furkanarius are we making this change? this is not really a bug, looks more like an improvement

**Comment by ArtemHryhorovGeniusee** [comment]
@furkanarius we can use cached list which we got on start. But in this case some nodes from list can be unavailable after some time.  At current realisation, every time when I need list I get cache and after that I trying to get new fresh data. So, using once(once on session) cached list is more quickly, but will have a little more unavailable nodes

**Comment by tadaskay** [comment]
@ArtemHryhorovGeniusee @furkanarius Created a separate issue for that: https://github.com/mysteriumnetwork/mysterium-vpn-mobile/issues/413

**Comment by tadaskay** [comment]
Still wrong in some screens, e.g. account
