### ISSUE TITLE
Content does not fit on the screen

### ISSUE THREAD

**Issue by tadaskay** [mysteriumnetwork/mysterium-vpn-mobile#401]
Device: Xiaomi Mi A3

- Filter presets
- Session history
- When connecting: "Cancel and choose..." button overlaps
- Never send ether… (doesn’t end with a dot so I assume the whole sentence does not fit)
- Identity address padding could be reduced to show all of the chars

![0364FBB8-11BF-4639-ABFA-02F1FBC75B7C](https://user-images.githubusercontent.com/4745368/123919497-a95d1d00-d98d-11eb-9356-0af067d10e40.jpeg)
![764D91BC-44B6-49BC-BF3E-CA7012CE16BF](https://user-images.githubusercontent.com/4745368/123919527-af52fe00-d98d-11eb-973a-8eefbc2fa38f.jpeg)
![70900400-CE68-4920-85B4-C96F5C0F6EE7](https://user-images.githubusercontent.com/4745368/123919533-b0842b00-d98d-11eb-8f6c-0e001a632936.jpeg)
![image](https://user-images.githubusercontent.com/4745368/123920288-76ffef80-d98e-11eb-9348-3fe6829aaa7f.jpg)

**Comment by Daria-Donchenko** [comment]
screen 1 - it's a scroll. If we need to change this we need some updates on the design.
screen 2 - originally it was accepted that node name and country name don't always fit. What is the expected result here?
screen 3 - this is a bug, totally agree, we will fix this
screen 4 - what should be the correct text?
@furkanarius

**Comment by furkanarius** [comment]
Let's at least fix screen 3. On screen 4, for the private key area, more characters could be shown. The padding area is a tad bit too generous. 
Screen 1 and 2 requires design changes, so this is to be discussed later
@Daria-Donchenko

**Comment by Daria-Donchenko** [comment]
@furkanarius noted

**Comment by tadaskay** [comment]
Filter presets should not be a scroll, but fit all items. Otherwise, on a bigger screen (e.g. Huawei P30 pro) it looks like this:

![screenshot-2021-07-15_11 23 55 403](https://user-images.githubusercontent.com/4745368/125756096-6e9d8eca-d637-40ee-8bb0-883fe7472f37.png)
