### ISSUE TITLE
Change private keys button does nothing

### ISSUE THREAD

**Issue by tadaskay** [mysteriumnetwork/mysterium-vpn-mobile#402]

**Comment by Daria-Donchenko** [comment]
it is not a button really, there was no requirement for this to be a button and lead somewhere. @furkanarius

**Comment by furkanarius** [comment]
@tadaskay do we have the functionality to change the private keys? If so, @Daria-Donchenko, we can add this as a feature so that the users can change their private keys.
If we have no such functionality, we should remove the text

**Comment by tadaskay** [comment]
@furkanarius We don't at the moment.
@Daria-Donchenko let's just remove it, I don't understand what that element is for.

**Comment by Daria-Donchenko** [comment]
ok, removing this then.
