### ISSUE TITLE
Written node pricing wrong in Android app

### ISSUE THREAD

**Issue by bpound** [mysteriumnetwork/mysterium-vpn-mobile#417]
The pricing for my node is wrong in the Android app. I changed the pricing weeks ago and it still hasn't been reflected in the written amounts in the app. However, the actual charged amount seems to be correct. I can only imagine this happens with other nodes too so that's why I write this here.

**Comment by ArtemHryhorovGeniusee** [comment]
@furkanarius is it related with android app or it's back-end problem that node price is incorrect?

**Comment by furkanarius** [comment]
@tadaskay Who should we talk to regarding the pricing updates on the application? Probably some APIs are not updated regularly

**Comment by tadaskay** [comment]
@bpound Can you write down ID of your node, provider set price and actual price that is shown in the app?

**Comment by bpound** [comment]
The node ID is 0x1c4573856d8918e18c6f8922d1ac6181898db05a

The price in MMN is 0.0005/hr , 0.2/GB, but in my Android app it shows as
0.0001/hr , 0.05/GiB.

**Comment by isaackielma** [comment]
Has this issue been resolved on your current app @bpound ?
