### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by Peter-SovietSquirrel** [mysteriumnetwork/mysterium-vpn-mobile#425]
App version 1.0.4.107108
Mi10T, MIUI 12.0.6

90% of the time app will stay with spinning icon when running the app.
![img_20210714_155118](https://user-images.githubusercontent.com/60095913/125785216-d3b9ae29-f7c0-4350-99a5-ab3f7d324cff.jpg)

[myst_andriod.txt](https://github.com/mysteriumnetwork/mysterium-vpn-mobile/files/6822869/myst_andriod.txt)

**Comment by ArtemHryhorovGeniusee** [comment]
Is this issue still relevant in the latest version?
1.0.5 is the last version for now

**Comment by Peter-SovietSquirrel** [comment]
The issue seems to be resolved in 1.0.5.
