### ISSUE TITLE
Add option to disabling filtering for supported nodes only in the Android app

### ISSUE THREAD

**Issue by soffokl** [mysteriumnetwork/mysterium-vpn-mobile#447]
By default, we are filtering unsupported nodes automatically. 
But there should be an option to disable this filtering if a user wants it. 
Users should be able to enable/disable in config such auto-detection.

This PR adds const to set NAT compatibility to `auto` https://github.com/mysteriumnetwork/mysterium-vpn-mobile/pull/446
Passing an empty string instead of `auto` will disable this filter.

**Comment by cvl** [comment]
Is there any specific use case why would anyone want to disable NAT compatibility auto-detection?

**Comment by tadaskay** [comment]
UI from desktop for this setting that you can use as a reference
![image](https://user-images.githubusercontent.com/4745368/132474714-94e32b3b-41ba-42cc-b17c-bd5b30ad9ae6.png)

**Comment by ArtemHryhorovGeniusee** [comment]
Implemented here:
https://github.com/mysteriumnetwork/mysterium-vpn-mobile/pull/455
