### ISSUE TITLE
x509: certificate has expired

### ISSUE THREAD

**Issue by pabloxid** [mysteriumnetwork/mysterium-vpn-mobile#456]
App gets blocked at opening, before showing anything, the little circle remains rotating. Loking at the logcat I see many errors like this:

E/GoLog: app/identity/registry/registry_contract.go: failed to contact hermes to get new registration status "could not request consumer data from hermes: could not execute request: Get https://testnet3-hermes.mysterium.network/api/v2/data/consumer/0x1f2e0870fee2ed0ffbb4bbc9a31e0bfc8c7ae603: x509: certificate has expired or is not yet valid.

**Comment by isaackielma** [comment]
This issue has been resolved. Please feel free to comment here in case issue still persists
