### ISSUE TITLE
Mysterium client on chromecast issues

### ISSUE THREAD

**Issue by jkimmel** [mysteriumnetwork/mysterium-vpn-mobile#458]
Describe the bug

I sideloaded an obviously older version of the Mysterium client onto Chromecast Android Tv. Because it was working I topped it up with 20 Myst. Now it is not working anymore, so how can I retrieve those 20 Myst?

Updating the app with the latest version without success.

Screenshots
I don't know how to get screenshots on Chromecast

Environment (please complete the following information):
I couldn't find neither the apps version nor the Mysterium identity of this device

**Comment by isaackielma** [comment]
Are you still experiencing this same issue with newest version? Looks like this issue was resolved awhile ago. Please comment here in case this issue persists
