### ISSUE TITLE
Can not import an account created with desktop client

### ISSUE THREAD

**Issue by MarkWieczorek** [mysteriumnetwork/mysterium-vpn-mobile#473]
I have backed up my mysterium desktop client account (on macos), and I would like to import this into my android mysterium client. However, in the anrdoid app, when I click on "import account" and then navigate to the backup file, it is impossible to select the file. The file is grayed out with a filename like "0x4j4kk...".

I understand that you can not use both clients at the same time with the same account. Nevertheless, I would like to permanently move my funds from the macos client to the android client, so this is not an issue for me.

**Comment by isaackielma** [comment]
Could you please reach out to help@mysterium.network so I can guide you along backup and importing steps? Looking forward to your response! 

Will be closing this issue and will reopen if it cannot be resolved after following up with user.
