### ISSUE TITLE
bug: Mysterium dvpn for android did not works.

### ISSUE THREAD

**Issue by adinetech** [mysteriumnetwork/mysterium-vpn-mobile#478]
**Describe the bug**
Mysterium dVPN does not work on Android.

**Expected behavior**
@EDWARDXcX (https://t.me/EDWARDXcX) from telegram reported me while opening the mysterium dVPN it just shows wifi error even while having 5Mbps download and upload speeds, he also tried with the wifi connection instead of 3G still didn't work.

**Screenshots**
![photo_2021-12-04 20 58 43](https://user-images.githubusercontent.com/68943180/144715271-429507f0-96a0-47d2-b6b3-ff6e43b0903e.jpeg)

**Environment**
 - OS: Android 7.0,
 - Android app version: 2.0.3,
 - Device/Handset mode: Benzo class 300s LTE,
 - Networking: 3G.

**Comment by isaackielma** [comment]
Is this issue still persistent @adinetech ?

**Comment by adinetech** [comment]
I don't think so.
