### ISSUE TITLE
>

### ISSUE THREAD

**Issue by Termuxtnt** [mysteriumnetwork/mysterium-vpn-mobile#494]
>  
>  ​rootProject​.​name ​=​ ​'​MysteriumVPN​'

_Originally posted by @Termuxtnt in https://github.com/mysteriumnetwork/payments-smart-contracts/issues/145#issuecomment-993440135_

**Comment by isaackielma** [comment]
https://github.com/mysteriumnetwork/payments-smart-contracts/issues/145#issuecomment-993440135

Closed as completed
