### ISSUE TITLE
Residential nodes not shown on smartphone if connected through mobile network

### ISSUE THREAD

**Issue by darkman1983** [mysteriumnetwork/mysterium-vpn-mobile#507]
I wondered, why both of my residential nodes are shown offline in Android VPN app.
I could repeat the following Steps:

1. Start app with beeing on mobile network
    1.1. Both residential nodes shown as offline
    1.2. Trying a search for the node id provides no result
![Screenshot_2022-01-14-18-41-16-662_network mysterium vpn](https://user-images.githubusercontent.com/553212/149562798-dd2f439c-d302-423f-80ea-f42071302de0.jpg)

Second approach:
1. Make sure to be connected through wifi
2. Start VPN app
  2.1. Nodes shown as online
  2.2. Also a search got a result
![Screenshot_2022-01-14-18-40-33-638_network mysterium vpn](https://user-images.githubusercontent.com/553212/149563018-7537f70e-3e6a-47c8-9c5d-fa493dd0256c.jpg)

As last step i also tried starting the VPN app while connected through wifi, go to favorites, disconnect from wifi and then connect to node with success.

Is this a bug or is it supposed that residential nodes not showing beeing on mobile networks?
Mobile ISP is o2.

**Comment by etherunit** [comment]
dVPN app is filtering out potentially incompatible peers (defining network (NAT) type) using combined results from stun checks.
