### ISSUE TITLE
Clarify: Which network to use for topup

### ISSUE THREAD

**Issue by veldspar** [mysteriumnetwork/mysterium-vpn-mobile#510]
When trying to topup via the app/desktop application a coingate link is created to provide payment.
What deterred me from doing this for now is that nowhere it is mentioned whether the topup address is a Ethereum ERC20 Token address for myst token or whether the topup address is a Polygon network ERC20 Token address. I assume its a ETH ERC20 address, however if so that should be clarified(or a popup added like "ONLY SEND MYST PAYMENTS FROM AN ETHEREUM ERC20 Wallet. Deposits sent using polygon will be LOST" or vice versa)
Considering that the ETH cost of topping up myst tokens likely exceeds any myst value being topped up, polygon should be supported for topups if it isnt already!

**Comment by isaackielma** [comment]
Issue has been ficed
