### ISSUE TITLE
Add BCH as payment method

### ISSUE THREAD

**Issue by Sermooh** [mysteriumnetwork/mysterium-vpn-mobile#512]
Add BCH as payment method. How it's done in the desktop app. Opportunities to make a payment with a low transfer fee are too few. It is unrealistic to pay with ERC-20 tokens and some can be removed.

**Comment by isaackielma** [comment]
Please note that we currently offer Polygon MYST top ups which are even cheaper than BCH. In case you have any issues topping up or any questions on how to do it with polygon MYST let us know and we can help you out! 😊
