### ISSUE TITLE
Can't import account 

### ISSUE THREAD

**Issue by Chukwulastson** [mysteriumnetwork/mysterium-vpn-mobile#608]
I can't import my account to another android device ..it keeps showing me inpute passcode

**Comment by isaackielma** [comment]
Could you please go to your old device and access your identity? Once you do that, please download backup file again and it will prompt you to create new passphrase. That passphrase should be your new password to use when migrating to new device.

Incase the issue persists, please contact us at help@mysterium.network and I will be able to guide you along! 😊
