### ISSUE TITLE
Balance is 0

### ISSUE THREAD

**Issue by Osama7895** [mysteriumnetwork/mysterium-vpn-mobile#626]
My mysterium account balance was about 18MYST but after I updated the app it became zero balance (its android version) please solve the problem 0x02eff1ef48b89b2a7f529fb2dd3a2b408e1f5996
![Screenshot_20220626-182742_MysteriumVPN](https://user-images.githubusercontent.com/108232323/175856388-c8b4b921-9e0b-4be2-8bf9-a97a79503d79.jpg)

**Comment by Osama7895** [comment]
And it's mobile app version (android)
![Uploading Screenshot_20220626-182742_MysteriumVPN.jpg…]()

**Comment by Donatas-MN** [comment]
@Osama7895 is this solved?
