### ISSUE TITLE
Wrong password message on newer app version

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/mysterium-vpn-mobile#693]
Currently using version 2.0.7, when updating version, the new update doesn't let me import my profile- get a "wrong password" message. 

Getting wrong password message, but when import is on older versions it works! Then account balance is 0.0000 which is false because i have over 15credits

Version 2.0.25 and lower lets import profile, but it shows balance is at 0.00. while from 2.0.27 to the latest version(2.0.32) doesn't let import happen (wrong password message)

<img width="381" alt="Screenshot 2022-09-01 at 05 39 24" src="https://user-images.githubusercontent.com/84313603/187871715-a5f5b313-83ba-4a1f-ae43-1bbb280a571f.png">

**Comment by licia2** [comment]
I am experiencing the same issue, please help

**Comment by Mustafa9507** [comment]
I am experiencing the same issue...please help

**Comment by licia2** [comment]
> I am experiencing the same issue...please help

Let's hope for their help

**Comment by roobank1** [comment]
![Screenshot_2022-09-05-14-00-27-420_network mysterium vpn](https://user-images.githubusercontent.com/37132606/188405015-920d5811-894b-4a00-aae4-cb2ae59c7eb8.jpg)
Experience same issue with lates Android app version 2.0.33 from Playstore
