### ISSUE TITLE
Ability to go fast (now too slow) (I suggested pulling the line)

### ISSUE THREAD

**Issue by Wjxfi** [mysteriumnetwork/mysterium-vpn-mobile#764]
Now it takes an incredible amount of time to spin just to get to the half, and it takes even longer to spin to the end. I suggest that when I pull the line to the right it will move much faster

https://user-images.githubusercontent.com/113500363/236179331-5b713da3-796e-429f-b20d-a587948f1dd1.mp4

you can do as you see below

https://user-images.githubusercontent.com/113500363/235224946-04529c03-f854-4b2f-8efc-2f8215e6d422.mp4

If you pull this line it will go much faster and not slow as it is now

**Comment by isaackielma** [comment]
Hello @Wjxfi !

Thank you for your valuable suggestion. I appreciate your input and will definitely provide feedback to our mobile development team regarding the possibility of adding this feature to our app. 

Good news that our new "monthly subscription" application will not have this issue. However, I will still check with our team to see if we can make the adjustment to our Android legacy app. I will keep you informed of any updates on this matter.

**Comment by isaackielma** [comment]
Was the example given from VScode?
